### ISSUE TITLE
Missing files in sdist

### ISSUE THREAD

**Issue by thatch** [dropbox/groupy#40]
It appears that the manifest is missing at least one file necessary to build
from the sdist for version 0.5.2. You're in good company, about 5% of other
projects updated in the last year are also missing files.

```
+ /tmp/venv/bin/pip3 wheel --no-binary groupy -w /tmp/ext groupy==0.5.2
Looking in indexes: http://10.10.0.139:9191/root/pypi/+simple/
Collecting groupy==0.5.2
  Downloading http://10.10.0.139:9191/root/pypi/%2Bf/1ad/29c5c7c4e97a7/groupy-0.5.2.tar.gz (7.3 kB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'error'
  ERROR: Command errored out with exit status 1:
   command: /tmp/venv/bin/python3 /tmp/tmp1grvinuh get_requires_for_build_wheel /tmp/tmp1w88i4_e
       cwd: /tmp/pip-wheel-48rhexd1/groupy
  Complete output (18 lines):
  Traceback (most recent call last):
    File "/tmp/tmp1grvinuh", line 280, in <module>
      main()
    File "/tmp/tmp1grvinuh", line 263, in main
      json_out['return_val'] = hook(**hook_input['kwargs'])
    File "/tmp/tmp1grvinuh", line 114, in get_requires_for_build_wheel
      return hook(config_settings)
    File "/tmp/pip-build-env-aojpb0bb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 147, in get_requires_for_build_wheel
      return self._get_build_requires(
    File "/tmp/pip-build-env-aojpb0bb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 128, in _get_build_requires
      self.run_setup()
    File "/tmp/pip-build-env-aojpb0bb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 249, in run_setup
      super(_BuildMetaLegacyBackend,
    File "/tmp/pip-build-env-aojpb0bb/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 143, in run_setup
      exec(compile(code, __file__, 'exec'), locals())
    File "setup.py", line 22, in <module>
      with open("requirements-dev2.txt") as requirements:
  FileNotFoundError: [Errno 2] No such file or directory: 'requirements-dev2.txt'
  ----------------------------------------
ERROR: Command errored out with exit status 1: /tmp/venv/bin/python3 /tmp/tmp1grvinuh get_requires_for_build_wheel /tmp/tmp1w88i4_e Check the logs for full command output.
```

**Comment by m-ynk** [comment]
Landed fix https://github.com/dropbox/groupy/pull/43
